# Generated by Django 5.0.7 on 2026-09-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('grade', models.CharField(max_length=2)),
                ('trip_type', models.CharField(choices=[('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International')], max_length=20)),
                ('max_flight_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('PREMIUM_ECONOMY', 'Premium Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], default='ECONOMY', max_length=20)),
                ('max_flight_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_hotel_category_stars', models.PositiveSmallIntegerField(default=3)),
                ('max_hotel_price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_train_class', models.CharField(default='AC 2-Tier', max_length=20)),
                ('advance_booking_days_required', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['grade', 'trip_type'],
                'unique_together': {('grade', 'trip_type')},
            },
        ),
    ]
