# Generated by Django 5.0.7 on 2026-09-08 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(choices=[('L1', 'L1 - Junior'), ('L2', 'L2 - Mid'), ('L3', 'L3 - Senior'), ('L4', 'L4 - Leadership'), ('L5', 'L5 - Executive')], default='L2', max_length=2)),
                ('cost_center', models.CharField(blank=True, max_length=50)),
                ('base_city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=30)),
                ('frequent_flyer_no', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
