# Generated by Django 5.0.7 on 2026-09-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('fiscal_year', models.CharField(help_text='e.g. 2026-2027', max_length=9)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['department'],
                'unique_together': {('department', 'fiscal_year')},
            },
        ),
    ]
